mqtt:
  broker: "127.0.0.1"
  port: 1883
  topic_sub: "agv/planner/global_path"

motor:
  speed_move: 0.5
  speed_turn: 0.5
  time_per_1m: 12.5
  time_per_90_deg_right: 3.05
  time_per_90_deg_left: 3.0
  offset_lateral_90: 0.01
  offset_longitudinal_90: 0 #-0.035

vision:
  model_path: "model.tflite"
  conf_thres: 0.5
  input_size: 300
  align_timeout: 0.5
  align_error_offset: 0.001
  turn_gain: 1.0
  servo_gain: 40

manipulation:
  serial_port: "/dev/ttyUSB0"
  baud_rate: 9600
  sensor_offset_x: 2.0
  grasp_threshold: 20.0
  distance_offset: 1.0
  height_offset: -5.5
  angle2_offset: 15
  angle3_offset: 25
  arm2_length: 9.5
  arm3_length: 16.0
  grasp_table:
    0: {'name': 'ampoule', 'angle': -30, 'height': 6.0, 'location': [0.2, 0]}
    1: {'name': 'choco',   'angle': -30, 'height': 3.0, 'location': [0.2, 0.85]}
    2: {'name': 'gru',     'angle': -60, 'height': 4.0, 'location': [-1, -1]}
    3: {'name': 'hulk',    'angle': -60, 'height': 3.0, 'location': [0.4, 1.4]}
    4: {'name': 'lipstick','angle': -45, 'height': 5.5, 'location': [0.4, 0]}
    5: {'name': 'minion',  'angle': -60, 'height': 2.0, 'location': [-1, -1]}
    6: {'name': 'shadow',  'angle': -30, 'height': 1.0, 'location': [0.2, 0.55]}
    7: {'name': 'thor',    'angle': -60, 'height': 3.0, 'location': [0.2, 1.4]}
    8: {'name': 'tissue',  'angle': -30, 'height': 3.5, 'location': [0.4, 0.85]}
    9: {'name': 'vitamin', 'angle': -45, 'height': 6.0, 'location': [0.4, 0.55]}

colors:
  0: [0, 0, 255]
  1: [0, 165, 255]
  2: [0, 255, 255]
  3: [0, 128, 0]
  4: [235, 206, 135]
  # Add other colors as needed